LEARNING_RATE: 1e-3
BATCH_SIZE: 64
EPOCHS: 100
IN_SIZE: 224
OUT_SIZE: 112
N_CLASSES: 1
AUG: True
WEIGHTS_URL: 'https://github.com/fchollet/deep-learning-models/releases/download/v0.6/mobilenet_1_0_224_tf_no_top.h5'
